import type { AnalyticsModel } from '../components/analytics-kit/types';

export const ttpaAnalyticsModel: AnalyticsModel = {
  name: 'TTPAPerformance',
  label: 'TTPA Operations',
  fields: [
    // --- Measures ---
    {
      name: 'calls',
      label: 'Total Calls',
      labelEn: 'Total Calls',
      kind: 'measure',
      dataType: 'number',
      format: 'number',
      description: 'Total volume of inbound and outbound calls',
    },
    {
      name: 'answered_calls',
      label: 'Answered Calls',
      labelEn: 'Answered Calls',
      kind: 'measure',
      dataType: 'number',
      format: 'number',
      description: 'Calls successfully answered',
    },
    {
      name: 'submissions',
      label: 'Submissions',
      labelEn: 'Submissions',
      kind: 'measure',
      dataType: 'number',
      format: 'number',
      description: 'Total submission forms sent',
    },
    {
      name: 'deals',
      label: 'Closed Deals',
      labelEn: 'Closed Deals',
      kind: 'measure',
      dataType: 'number',
      format: 'number',
      description: 'Total deals won / closed',
    },
    {
      name: 'students',
      label: 'Enrolled Students',
      labelEn: 'Enrolled Students',
      kind: 'measure',
      dataType: 'number',
      format: 'number',
      description: 'Total students enrolled',
    },
    {
      name: 'avg_duration',
      label: 'Avg Duration (sec)',
      labelEn: 'Avg Duration (sec)',
      kind: 'measure',
      dataType: 'number',
      format: 'number',
      description: 'Average talk time on answered calls (seconds)',
    },
    {
      name: 'submission_rate',
      label: 'Submission Rate (%)',
      labelEn: 'Submission Rate (%)',
      kind: 'measure',
      dataType: 'number',
      format: 'percent',
      description: 'Submissions per call percentage (Submissions / Calls)',
    },
    {
      name: 'deal_rate',
      label: 'Deal Conversion Rate (%)',
      labelEn: 'Deal Conversion Rate (%)',
      kind: 'measure',
      dataType: 'number',
      format: 'percent',
      description: 'Deals closed per submission percentage (Deals / Submissions)',
    },

    // --- Dimensions ---
    {
      name: 'representative',
      label: 'Representative',
      labelEn: 'Representative',
      kind: 'dimension',
      dataType: 'string',
      description: 'TTPA team representative / SDR name',
    },
    {
      name: 'date',
      label: 'Date / Period',
      labelEn: 'Date / Period',
      kind: 'dimension',
      dataType: 'time',
      description: 'Time dimension for operational events',
    },
    {
      name: 'form_source',
      label: 'Form / Source',
      labelEn: 'Form / Source',
      kind: 'dimension',
      dataType: 'string',
      description: 'Lead capture form name or source',
    },
    {
      name: 'direction',
      label: 'Call Direction',
      labelEn: 'Call Direction',
      kind: 'dimension',
      dataType: 'string',
      description: 'Inbound or Outbound',
    },
    {
      name: 'answered',
      label: 'Answered Status',
      labelEn: 'Answered Status',
      kind: 'dimension',
      dataType: 'string',
      description: 'Whether the call was answered (true/false)',
    },
  ],
};
