import { useEffect, useState } from 'react';
import { ShieldCheck, Trash2, UserPlus } from 'lucide-react';
import { createTranslator } from '../i18n';
import type { AnalyticsKitRepository, AnalyticsLocale, AnalyticsUser, DashboardGrant, DashboardPermission, KitDashboard } from '../types';

export function AccessManager({ dashboard, repository, users, locale = 'pt-BR', disabled = false }: { dashboard: KitDashboard; repository: AnalyticsKitRepository; users: AnalyticsUser[]; locale?: AnalyticsLocale; disabled?: boolean }) {
  const t = createTranslator(locale), [grants, setGrants] = useState<DashboardGrant[]>([]), [userId, setUserId] = useState(''), [permission, setPermission] = useState<DashboardPermission>('view');
  useEffect(() => { repository.listGrants(dashboard.id).then(setGrants); }, [dashboard.id, repository]);
  const save = async () => { if (!userId) return; const grant = await repository.saveGrant({ dashboardId: dashboard.id, userId, permission }); setGrants((current) => [...current.filter((item) => item.userId !== userId), grant]); setUserId(''); };
  const remove = async (id: string) => { await repository.deleteGrant(dashboard.id, id); setGrants((current) => current.filter((item) => item.userId !== id)); };
  return <section className="ak-access"><header><ShieldCheck size={18} /><div><strong>{t('access')}</strong><span>{locale === 'pt-BR' ? 'Permissões deste dashboard' : 'Dashboard permissions'}</span></div></header>{!disabled && <div className="ak-access-form"><select value={userId} onChange={(event) => setUserId(event.target.value)}><option value="">{locale === 'pt-BR' ? 'Selecione um usuário' : 'Select a user'}</option>{users.filter((user) => user.id !== dashboard.ownerId).map((user) => <option key={user.id} value={user.id}>{user.name} · {user.role}</option>)}</select><select value={permission} onChange={(event) => setPermission(event.target.value as DashboardPermission)}><option value="view">{t('viewer')}</option><option value="edit">{t('editor')}</option><option value="admin">{t('administrator')}</option></select><button type="button" onClick={save}><UserPlus size={15} />{locale === 'pt-BR' ? 'Conceder' : 'Grant'}</button></div>}<div className="ak-grants">{grants.map((grant) => { const user = users.find((item) => item.id === grant.userId); return <div key={grant.userId}><span><b>{user?.name ?? grant.userId}</b><small>{user?.email}</small></span><em>{grant.permission}</em>{!disabled && <button type="button" onClick={() => remove(grant.userId)}><Trash2 size={14} /></button>}</div>; })}{!grants.length && <p>{locale === 'pt-BR' ? 'Somente o proprietário e administradores têm acesso.' : 'Only the owner and administrators have access.'}</p>}</div></section>;
}
